kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: helloworld-app-route
  labels:
    app: helloworld-app
    apps.open-cluster-management.io/do-not-delete: 'true'
spec:
  to:
    kind: Service
    name: helloworld-app-svc
    weight: 100
  port:
    targetPort: 3002
  wildcardPolicy: None
