apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app-degraded-deploy
  labels:
    app: helloworld-app-degraded
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: helloworld-app-degraded
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-app-degraded
    spec:
      containers:
      - name: helloworld-app-degraded-container
        image: "quay.io/fxiang1/helloworld:0.0.1"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3002
        env:
          - name: "PORT"
            value: "3002"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          request:
            cpu: 50m
            memory: 64Mi
