kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
  annotations:
    apps.open-cluster-management.io/do-not-delete: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi